locators={
    "login_page": ["https://www.ikea.com.tr/"],
    "enter_for_login_page": ["https://www.ikea.com.tr/uyelik/uye-girisi.aspx"],
    "login_button":["/html/body/form/header/div[2]/div[1]/ul/li[1]/a/span"],
    "signup_button" : ["/html/body/form/section/div[1]/div[1]/div[1]/div[1]/div[7]/div[1]/strong/a"],
    "new_form_name" : ['//*[@id="ctl00_ContentPlaceHolder1_ctrlRegister_txtFirstname"]'],
    "new_form_surname" : ['//*[@id="ctl00_ContentPlaceHolder1_ctrlRegister_txtLastname"]'],
    "new_form_email" : ['//*[@id="ctl00_ContentPlaceHolder1_ctrlRegister_txtEmail"]'],
    "new_form_bday" : ['//*[@id="ctl00_ContentPlaceHolder1_ctrlRegister_txtBirthdate"]'],
    "new_form_password" :['//*[@id="ctl00_ContentPlaceHolder1_ctrlRegister_txtPassword"]'],
    "new_form_repeat_pass" :['//*[@id="ctl00_ContentPlaceHolder1_ctrlRegister_txtConfirmPassword"]'],
    "new_form_mobile_no" :['//*[@id="ctl00_ContentPlaceHolder1_ctrlRegister_txtPhone"]'],
    "new_form_sex" : ['//*[@id="ctl00_ContentPlaceHolder1_ctrlRegister_ddlGender"]'],
    "gender_choise" : ["/html/body/form/section/div[1]/div[2]/table/tbody/tr[4]/td[2]/select/option[2]"],
    "ikea_check_box" :['//*[@id="ctl00_ContentPlaceHolder1_ctrlRegister_chkTerms"]'],
    "notification_box" :['//*[@id="ctl00_ContentPlaceHolder1_ctrlRegister_rejection"]'],
    "register_button":['//*[@id="ctl00_ContentPlaceHolder1_ctrlRegister_btnSubmit"]'],
    "pin_text_bar":['//*[@id="ctl00_ContentPlaceHolder1_ctrlRegister_btnSubmit"]'],
    "recaptcha_checkbox" : ['/html/body/div[2]/div[3]/div[1]/div/div/span/div[5]'],
    "finish_register_button" : ['//*[@id="ctl00_ContentPlaceHolder1_ctrlRegister_btnSubmitActivation"]'],
    "member_email_textbox" : ['//*[@id="txtEmail"]'],
    "member_password_textbox" :['//*[@id="txtPassword"]'],
    "member_captcha_button" : ["/html/body/div[2]/div[3]/div[1]/div/div/span/div[5]"],
    "member_login_button" : ['//*[@id="btnLogin"]'],
    "email" :["nilarolat@gmail.com"],
    "password" :["nilABC1919"],
    "new_signup_link" : ["https://www.ikea.com.tr/uyelik/yeni-uyelik.aspx"],
    "Message" : ["/html/body/form/section/div[1]/div[1]/div[1]/div[1]/div[1]"],
    "Message2" : ["/html/body/form/section/div[1]/div[6]/table/tbody/tr/td/div/div/label"],
    "title":["/html/head/link[1]"],
    "IKEA_MAGZA" :["/html/body/form/header/div[1]/ul[1]/li[1]/a"],
    "product_search_box" : ['//*[@id="txtSearchBox"]'],
    "search_button": ["/html/body/form/header/div[2]/div[1]/div[2]/a"],
    "alertx": ["/html/body/form/section/div[1]/div[2]/div[3]/div[1]/div[1]/div/i"],
    "product_price" : ["/html/body/form/section/div[1]/div[4]/div[3]/div[1]/div[1]/div[1]/div[2]/span"],
    "product_name" : ["/html/body/form/section/div[1]/div[4]/div[3]/div[1]/div[1]/div[1]/div[2]/h4"],
    "product_info" : ["/html/body/form/section/div[1]/div[4]/div[3]/div[1]/div[1]/div[1]/div[2]/p"],
    "more_info" : ["/html/body/form/section/div[1]/div[3]/div[2]/div/ul/li/a"],
    "rasgele_bulunan_no" : ["/html/body/form/section/div[1]/div[2]/div[1]/h3/strong[2]"],
    "stock_store_control" : ["/html/body/form/section/div[1]/div[4]/div[2]/ul/li[3]/a"],
    "stock_control_combobox" : ['//*[@id="ctl00_ContentPlaceHolder1_ddlStores"]'],
    "combobox_izmir" : ["/html/body/form/section/div[1]/div[4]/div[3]/div[3]/div/div[1]/select/option[7]"],
    "check_stock_button" : ['//*[@id="btnCheckStock"]'],
    "stock_text" : ['/html/body/form/section/div[1]/div[4]/div[3]/div[3]/div/div[2]/p[2]/span[2]'],
    "bize_ulasin" : ['/html/body/form/header/div[1]/ul[1]/li[6]/a'],
    "izmir_sube" : ['/html/body/form/footer/div[1]/div/div[3]/ul/li[6]/a'],
    "izmir_adress" : ['/html/body/form/section/div[1]/div[4]/ul/li[1]/p[2]'],
    "facebook_link" : ['/html/body/form/header/div[5]/div[2]/a[1]'],
    "twitter_button" : ['/html/body/form/header/div[5]/div[2]/a[2]'],
    "pinterest_button" : ['/html/body/form/header/div[5]/div[2]/a[3]'],
    "pinterest_link": ['https://www.pinterest.com/ikeaturkiye/']






}